= Hi, my name is Mahendra Gudhakesa.
:hp-tags: about

I am a Jakarta-based qual researcher. I graduated University majoring in Civil Engineering (don't get me started on how I got there), before finally indulge my interest in social sciences, and a horizontal career path. 

I spent most of my professional days working in Market Research Industry. I observe people, make sense on why they behave like they do, or connect brands and businesses to their customers. Not only have worked with big multinational companies, often times I can be found working with small businesses and startups building great experiences and stories.

I love good literature. I spend most of my leisure time reading. Other times, I'd just ramble words to this page. 

Throughout my life, I have been lucky enough to work with business owners, creative people, designers, musicians, writers, photographers, tech startups, or even data scientists. I am always looking for opportunities to collaborate and to create stuff. Feel free to nudge me anytime.

A few other things I am known to be doing:

*_I Write_*

I am a writer, or I could say I try to be one. I do this because most of the times I found my fingers doing a better job describing my thoughts compared to my tongue. I am a registered contributor to EliteDaily, a growing online platform made by millennials, for millennials. I also have a page in Medium. Sometimes, I write on other place. The pieces that didn't made it through anywhere, goes right on this site. I call this site clipboards of unprocessed phrases and sentences of the unfulfilled intent.

*_I take pictures_*

I believe great pictures tell compelling stories. And if words fail me, I resort to visuals.

*_Freelance Qualitative Researcher_*

Within my time, I had been involved in many research projects across categories like FMCG, online media, e-commerce, banking, telecommunications, or automotive. I conducted numerous FGDs, IDIs, ethnography, or desk researchs (often just for the fun of it). I had been exposed to work with different business and research objectives such as concept checks, communication checks, U&A, and UX research. (For lists of extended clientele, email me at mahendra.gudhakesa@gmail.com)

Being a millennial in body and soul, my currrent interest now is on youth lifestyle and generational studies (Gen Z, I'm watching you).