= The Horizontal Career Path: A Discipline of Flexibility and Adaptability In The Modern World
:hp-alt-title: A Horizontal Career Path
:hp-tags: words, career, work, millennials

Switching job is never easy. When you dedicate yourself climbing some corporate ladder, holding an establishsed professional position doing certain things, it takes certain degree of habit and experience. Switching out to other job is understandable a nuisance. The idea of having to adapt to new environment, new working habit, new people, and new responsibilities, could be one of many sources of anxiety towards our work.

There are also specific fears associated with having to switch jobs. We all wanted our next job to be better compared with our previous ones. Whether it’s better benefits, better flexibility, better teams, or for many, what’s often considered is whether it has better pay.

Being in the late 20s, I have witnessed lots of people around me telling stories about them wanting to go out of their current job. Most of them feel unfulfilled, or unhappy with their current career. Being a millennial in spirit, I often say to them, “well, why don’t you? Just quit, resign, or whatever, find something else you’d like to do in life. I believe that the world still have a lot to offer you.. “

It turns out, most friends and colleagues often found my statement to be hard to swallow. There are always a glimpse of confusion, or rejection towards the idea I threw at them.

“It’s not that easy… “ Some say to me.

I’m curious on how it’s not that easy. Very carefully they elaborate further on why. It turns out, some of my friends (who now had made it into the mid-management in some big corporations) find it hard to find a replacement job which offers the same kind of responsibility (or more), but with better pay. Salary or pay seem to be one of the main consideration to switch job. Even when one is unhappy with their current work, having the prospect of having a job with lower pay often considered not the way to go.

I get it, finding a company that could give you better pay, is indeed hard. Especially if you had made it to obtain an 8 figure IDR a month from a mid-management position. And the reality of the specific industry also play a role. If you’re a mid-management in an EPC or construction firm in Indonesia, good luck finding good opportunity for a better position WITH better pay. The whole industry landscape had saturated itself up to a point that career progression often means a considerable dead-end.

So then I say, “why don’t you switch companies? Or industries?”. I found that my last statement is even harder to swallow among them.

The main source of anxiety towards switching jobs or careers, often stem from the fear of starting over from the bottom of the ladder again. Starting over from the bottom ALWAYS means having less paycheck. And the problem with having lesser paycheck is that most people don’t feel like they’re “progressing”, or in control of their life “progress”. Having to start over, is considered a setback.

Well, this idea is what I’d like to challenge.

When I graduated, I was definitely starting over. I don’t directly go to EPC or O&G companies to exercise my university expertise. In fact I decided to jump abroad into the marketing and design field. It was definitely hard at first. There are lots of new stuff I had to get accustomed to. There are lots of industry know-how I had to catch up. There are lots of details I need to re-learn.

Halfway to the top, I decided to make another shift to the research industry. And this time, I also had to re-learn all the know-how. And the pay? I receive lower amount compared to my previous job.

Then I move again to another startup company, still doing research stuff. I receive lower take-home-pay per month again. But the opportunity is huge. There are more potential exposure to clients and other small businesses, There are more things to do other than just doing research per-se. And a couple of years later. I ended up working with startups, ecosystem builders, photography schools, and many other things.

I often ask back to my friends and colleagues. Judging by my experience, was I progressing? Was receiving lower salary in each job-change means that I was progressing backwards? Comparing my friends stories with mine, I often ask myself, what is progress anyway?

Contrary to what my friends think, the way I see progress isn’t about the rising amount of a monthly salary. Progress, for me is about diversification of my skills and my work portfolio. It’s more about the expanding networks of people you’ve worked with, or the kind of activities you do differently in each job-change. Progress doesn’t always have to go in a vertical direction. Progress could go sideways, or horizontally.

And believe me. The more you expand your ways horizontally, it comes easier and easier each time you do it. And what I came to realise later from my experience, that this encounter, is what I call the reduction of transaction cost.

Transaction cost is an intangible cost experienced when you were starting things over, or building back from scratch. Transaction cost occur alongside the hardship of starting anew, on re-learning new things, acquiring new knowledge, and working with new people.

The more I went expanding my skills and horizon, the less the transaction cost in my next job becomes. And I guess, this concept is kind of overlooked by people in mid or late 20s like my friends. It’s such a pity because often life give us many chances and opportunities, many open doors. And as the world is changing, our ability to adapt is more tested than before.

Once again, I am not against corporate careers and stuff. But I believe that one of the survival skill in the modern world is having to adapt quicker to modernity. And when we talk about progress, beside thinking about careers and paycheck-progression, it’s worth looking at progress from the point of view of investing on our flexibility across careers, and reducing transaction costs.

After all, doesn’t old wisdom always say to us: “Don’t put all your luck in one basket?”