= On Finding Your Writing Voice
:hp-alt-title: a beginner's writing guide
:hp-tags: words, writing, bloggin

Writing now has become an unfashionable craft. In midst of vlogs and podcasts, the art of making a point through threaded letters and well-crafted diction is diminishing. At least that’s the way I see it.
We live in times when we’re obsessed to get our points across to our audiences as fast as possible. Our point of view should be conversational, and as succinct as a 30-seconds pitch.

While there’s nothing wrong with it, I still long for a writing culture in which it emphasize more on the power of words. To write is to impose tone and manner without the help of facial expression and audible emphasis. This is the craft I’d like to submit my devotion to at the moment.

I am always drawn to books and ideas. From classical writers to contemporary philosophy. Though letters, words, and writings will never cease to exist in our world, it is important for us to give more attention and discipline to it.

One of the hardest thing in doing so, is to find your own voice. A constant, unchanging point of view, tone, manner, that could narrate a blank sheet of paper, or a blank white LCD screen. Finding your own voice could be a never-ending journey. It may take a lifetime. But I’d like to share some quick tips on how to find your own voice, and start your journey to the craft of writing.

*Write more, write often*
The most important thing for me to start this journey, is to write more and write often. Writing is not an overnight mastery. It took many hours, days, or years of constant dialogue with your inner self. Writing is not a virtue, it’s merely a habit.
There are no better advice I could share to people wanting to start to write, other than: write.

*Be Self Aware, Constantly*
I remember once I could write more than 4 pieces a night. There are more times I remember having difficulties to write a piece in 4 months. I call it the low days and the high days. When it happens, accept it. But also try to understand why it’s happening to you.

Ask yourself questions. Have you dedicate enough time to have a dialogue with yourself? Have you take enough time to actually sit still, and think about the things you’ve been through? Have you dedicate a little more time to make yourself comfortable with a pen and a notebook? Or a distraction-free writing app beside netflix?

Low days and high days happen only because we decided (both intendedly or unintendedly) to put our focus on the things that surround us. It took a certain degree of self awareness to actually realize whether the things we give attention to, on a certain time period, will be beneficial in developing your writing.

*Lastly, put your inspirations down*
In times of endless reference and inspiration, it’s always easy to get immersed in hours of book reading, blog reviewing, or youtube watching. We live in time where millions of good (and also bad) literature pop in front of our eyes wanting to inspire, or simply be seen.

Inspirations are good, but also acknowledge the fact that it consumes your attention. And your attention is the only thing that’s keeping you away from that blank page.

A good book, or a good inspiration, also need to be put down. Because in the end, it silences your own voice. And your voice is the only thing that matter in your journey of writing, or word-crafting.