= Caught In The Middle
:hp-tags: words

My dream to be a writer, or at least to constantly write, is actually a recent aspiration. I have developed my love for writing in my late university years. I remember it was my only way to express a late-teenage angst, and then the habit stick.

I love writing the way it function like an emotional outlet. Like a faucet for my overflowing emotions, thoughts and ideas. Writing is like taking my daily dose of drugs. Like an amphetamine, it helps me focus and lost at the same time. It keeps my mind afloat, yet my feet on the ground.

I am of course, lately in deep disappointment. Seeing my own writings to be not as productive as I hoped to be. And I kept wondering why, and how could this happen. So I contemplate.

Writing is like one important tool for one's linguistic mastery. And linguistic mastery, for me, isn’t about communication per se. It’s about a discipline of thought. The way you manage your logic is detrimental to how you use language, and what language do you use.

I am, by default, a bilingual. In one side, I enrich my knowledge with English books and literature, yet I must function properly in most aspect of my life using my mother tongue. To some extent, I could feel the mastery of both language conflicts inside my head. And the conflict isn’t about diction or vocabulary, but more about point of views. The two language seem to have a polar thought structure. One rich in expression, the other functional. One heavy on analogy, the other rich in vocabulary. I often found myself confused and simply brain dead trying to retrieve words or threading sentences into a paragraph. Not only in writing, but also on verbal occasions.

I remember a research that mention human can’t really do, or focus at two things at one time. When it comes to the use of language, it does make sense. One can’t simply think and speak in two languages with different roots. Some people can speak english, while mixing up with a little french and Spanish. That’s understandable because those languages have the same root: Latin. The words different, the grammar different, but I can argue that all of those language share the same structure and discipline of thought. It was conceived out of cultures with many shared values.

I realised that maybe the fact that I’m stuck between two languages is the main barrier for my unproductive writing habit. I can’t seem to pinpoint words to use, or even usable expressions. I can’t decide clearly on how to narrate or describe a particular tone and point of views. I feel like my thoughts are caught in the middle.

I miss the moments where I could remember words flowing out of my fingertips seamlessly, faster than my tongue muster a syllable. I do miss the fluidity of words that runs in the back of my head each time I’m engage in a certain topic. It’s just that, now it isn’t happening. Or at least it’s not happening as often as I hoped it should.