= The 5 types of Millennials In The World
:hp-tags: words, millennials, generation Y, qualitative, research

With myself belonging in the millennial generation, it's always interesting for me to observe my own generation. It's one of the ways I reflect back at myself, my decisions, and my view of life. And being involved in qualitative research often give me a profoundly general point of view in explaining my generation. 

What makes a millennial different compared to previous generations is the fact that we grew up with the internet. We millennials remember making our first email addresses, from services that are probably obsolete by now. We all experienced lifestyle changes through internet and technology, through gadgets and gizmos. Global connectivity is the excalibur to the modern day king Arthur, and I guess we're the first generation who democratizes its full power.

They way internet is changing our lives is by giving us two things. One, is the democratization of knowledge, and secondly is the disruption of our social conduct. Internet had enabled us to access information previously limited to certain cultures or countries. The birth of knowledge without boundaries had made us more critical than ever before. This of course, would affect how we live our social lives today. The way we interact with people is different compared to the young people in the 80s. We spend most of our times with friends, with our eyes glued to smarthphone screens. We could have lively discussions and chats without any lip movements, just a few tap of the thumbs.

So, these democratization of knowledge, and disruption of social conduct. What do they bring us? Those things had brought us to a state where we're naturally inclined to challenge any status quo or hegemony. We have access to vast amount of information now, so we challenge, we ponder, we tweak, we hack, and we question endlessly. Now that sounds like a millennial to me.

There are no generation that have the drive to challenge the hegemony as hard as the millennials. This is due to the fact that the internet penetration among the global citizen is exponentially faster compared to other technological advancement.

So most of millennials now have that call to change or challenge things. It's more common for us millennials to argue with our parents or our teachers. We challenge institutions more openly, and we go as far as we can imagine. The conflict resolution between parents and millennial children had evolved into something unimaginable in previous times.

The question now is how do millennials cope or deal with that call to change and to challenge? Bearing that question in mind, here are the five types of millenials.

*The Straight Trajectories*

These are the millennials who live their lives as if they're living a straight line. The main key of living life for these straights are living life on repeat. They like to repeat success stories that are told to them, and live life accordingly. If my parents are lawyers, I'd get myself into law school too, because I know that being a lawyer is promising. If my parents say that working in a multinational company would benefit me, I'd do it. These millennials simply doesn't embrace the true calling of being a millennial. They usually live their lives through the eyes and values of the previous generations.

Their simplistic, or somewhat naive approach to life is actually something we should give respect to. We have known that it's harder than ever to keep life on track with different realities of modern days economy. These type of millennials work their way through career choices with ease and seamlessly. They're the ones who had decided their direction of life before life even happens for them.

*The Anarchist*

A polar example compared to the previous, this type of millennials focus their life on fighting against the current norm or hegemony. If society expect me to live in a certain way, the way I'm going to do it is act the other way around. If the way to live means having to indulge myself in a 9-to-5 jobs, to hell with it. These millennials will refuse to be bound by any rules or social conduct. They challenge everything in search for a better form of life. They embrace the call to change and challenge as their way of life.

Despite the anarchist nature of these types, they're actually the most exposed to life experiments and opportunities. They are the first kind to create new things and able to make things happen. They make businesses happen, or making social impact heard. A lot of social revolution in world's history came from these people unbound to rules and boundaries. There are huge probability that the next best thing in the world, comes from these type of millennials.

*The Compromiser*

If life is like a circus act, then life for these millennials are like balancing a tightrope. They're mainly focused on keeping balance between their inner calling as millennials, and maintaining society's standard and expectation. A life form mostly found in emerging Southeast-Asian countries like Malaysia and Indonesia, but we might find these types lurking in most progressive cities of the world. These types often find themselves compromising their dreams in order to please certain social practices. These millennials see compromise as a way out. A balanced and proactive approach to life, with goals to please as many lives as possible; starting with their life, and other people that surrounds them.

But it's not entirely bad. One of the things we should appreciate from these type of millennials is their ability to manage multiple goals at once. They could be having a prestigious job in an international company, while also making businesses on the side. They're the ones who is dying to change their way of life, while also being respectful to social norms and values.

*The Disconnected*

A special case within millennials, these types resembles what most people remember being the punk-rock or emo kids in the early 2000s. These type of millennials usually have clear direction on where they want to go, but they don't show it to others. They have this calling to challenge or to change, but they don't preach about it. However, compliance to current society's standard also not in their agenda. To most, they would seem like lost people. They tend to be reserved individuals to most.

However, not everything is grim about these millennials. What we can learn from them are the willpower and endurance they had shown throughout their adolescent life. Though self-reserved, these types had proven to be the people who think and feel deeply. They face adversities in the most enduring way possible. Their perception towards life are inevitably useful and inspirational for other people in getting through life. Their story of perseverance and enduring life could prove to be meaningful for all of us.

*The Artist*

The last type of millennials, I often like to call the lucky ones. These are the rare types that usually made the world go round in their own orbit, effortlessly. The ones that have the calling to change and challenge, yet the world is conspiring with them in creating the changes they want to happen. These type of millennials usually doesn't have much external factors to fight against in making their dreams happen. They simply have to be stubborn enough to do the things they love.  Things are provided, or easily come to their way. Their main challenge is self-reflective, and all about overcoming one's own demon.

The way that they're lucky, is because they usually could dedicate themselves fully on their road to self-development. They could be wanting different things compared to other people, yet the world gives them just that. They could be wanting to indulge their lives fully on the road to artistry and creation, or simply to have a job that society doesn't want to have, yet they can do it with ease. For example, a son of a banker and investment broker who wanted to be a writer and scholar, and he worked his way through it with ease.

In the end, there are no types of millennials better than the other. Eventually our own adversities and challenges shapes us the way we are today. And it's no use for us to regret the things that happened to us in the past. Our challenges and calling only will shape our decisions the way it suits us. It's important for us to understand well, which types do we belong to, to question ourselves, to reflect back on what made us into the millennials we are today. Eventually we're required to combine forces together, shaping our world the way we envision it to be.