= Learning To Be Present
:hp-tags: words

I remember a few months ago, when I attended a workshop on drawing and painting. it was an open event, commissioned by local artists and painters for the general public. The main goal of the event is to introduce the fundamentals of drawing to the general public. The initiator of the events, the artists, believe strongly that anyone can draw, and it only takes a few correct approach to drawing to unleash the hidden talent in all of us.

So they first open the workshop, telling us to draw a bowl of fruits in front of the room. And so I did. Of course I failed miserably. All I left on the piece of paper was a bunch of poorly-drawn bananas and oranges with incorrect order and shades.

I was later told that, the key for a successful, life-like drawings are when we perceive the object we'd like to draw just as it is, not as we thought it should be. I was dumbfounded at first, trying to make sense of whatever it is I have been told.

But later on I got the point. My failure to draw is because I constructed bananas and oranges the way I remembered how bananas and oranges are shaped. I didn't draw my bananas and oranges the way it is as presented in the bowl in front of me. I linger more on the shape of hundreds of bananas and oranges' I've seen, rather than the actual shape of the bananas and oranges in front of me.

In my work as a qual researcher, I often got annoyed with a problem of not being able to understand why do people behave like they do. Why do people would use bing instead of google? Why do people like to eat tempe instead of tahu? It was always later I realized, the reason I am not able to understand them, is because I was actually asking: why don't people behave like I do? If I am able to perceive the way people live the way they are, also with their realities and contexts, I would not have the same annoyance. I would make research reports better and faster and also made more sense.

These series of things, which taught us to perceive things the way they actually are, in contrast to how we constructed the things based on our experience and memories, play a very important role in how we approach life. In specific, it taught us to deal with a happy life.

The key for a happy life is when we could perceive life as it is in front of us, not based on our constructed ideals and memories about the things that made us happy. Our previous excitements, memories, and experiences are constantly building aspirations and longings in the back of our head. These images and aspirations stays there, clouding our vision to really see life the way it is actually presented in front of our eyes. We fail to see a good life, because what we do is actually compare and contrast our current context with a previous reality that is obsolete.

It is impossible to understand life as comprehensive as we might hoped, if we keep lingering on the good memories we had. Good things in the past happens because of the past's context and reality. What we consider good in the past, could not possibly be as good if we experience it now, because we're facing a different reality. We often seek happiness in life the way we expect a perfect deja vu moment of our previous exhilaration. While we all no, there is never a perfect deja vu moment in life.

That is why, I think we should learn from artists, painters, photographers, or qual researchers. We should always be reminded that great beauty, or great reality, are always represented when we learn to be in the present. When we draw, copy, capture, or describe the current experience the way it is actually presented in front of us.

In times of anxiety and anxiousness. It's worth trying to get a bunch of bananas and oranges on a bowl, and try to draw it. Remember that we need to approach our current reality the way we draw the perfect bananas and oranges. By really making sense of what it really looks like in front of our eyes. Not by comparing them to previous bananas and oranges, and not by worrying about what our future bananas will look like.

Have a banana!