= The Allure of The Corporate Career Path
:hp-alt-title: On choosing careers
:hp-tags: words, millennials, work, entrepreneurship

I graduated university in July 2011. I obtained my bachelor degree from one of the most notable public university in the country. Although there are some friends who chose to go through the traditional career path like they were prepared for, at that time I remember what trend is going on among us fresh graduates. That is the allure of starting your own company. And long story short, that’s what I did.

Right after graduating, I started a small branding & design firm based in Jakarta with a couple of friends. The time was good back then, and we were proud. We might not have much money to make at first, but we do appreciate the flexibility and versatility on the way we work. We hang out with clients, spend time more with them as they were our friends and partners. And to my generation, that is exactly what matters most when you start out into the professional world. The potential for meaningful connections and the meaningful work we could do is always right under our noses.

I never regretted this decision in my life. I continue life, treat it as series of open doors and opportunities, and still believing that the future of young people around me will be like what I perceived it to be in 2011. I believe that more and more people in the upcoming future, will follow the path I’ve chosen.

Five years straight to 2016, I really thought the world had progressed the way I thought it would be. I thought that there will be more and more people who are like me when they graduate, wanting to make more business out of their interests and passion. That turned out to be false.

*The Supply Had Not Met The Demand*

Some time ago, I met a long-time friend of mine, an HR specialist working in the big corporate world. We talked a lot about the current youth reality, and what she said to me is rather surprising. At least more than 80% of fresh graduates she met between the year 2015 and 2016, are all still interested to get into the corporate world. So, the trend isn’t changing as much as I thought it would be in 2011.

That fact alone strikes me as unusual. While in my experience working closely with HR departments from big companies, I often heard they were having difficulties in recruiting the right people for their organisations. But the reality among the fresh grads are: more than 80% of them actually want to get into the corporate world. We got one side complaining about not able to find the right people for their job. But the other side, the fresh grads side, hundreds of thousands of people each year are ready to kill for a decent position in those organisation.

So I asked her further about her experience working in her company. How do the young people perform? The pain in the ass for her is having to look at the employee turnover report that reached 65% a year.

So I get it. Majority of fresh-grads (80%) wants to work in big corporations after they graduate. From all that made it through, 65% of them probably quit their first job in the first year.

 — -
 
I’m curious and a little bit perplexed. So I decided to dive deeper into this reality. I would like to know what is millennials’ aspiration when it comes to work. Or to be more specific, what are the things they aspire to do after graduating?

Yes, I can’t deny it, although the popular media now are heading to the utopia of entrepreneurship, craftmanship, and pursuing your interest, the majority of university students we met still aspire in getting into the corporate world.

The reason behind it was pretty much straightforward, and not that different from what my parents had taught me. The promise of a fix income in midst of uncertain economy, or the potential to be exposed in numerous job description, and work location. It’s well understood that for these millennials, the main allure of the big corporate world for them, mostly come from Management Trainee programs, ODPs, and other programs alike.

Of course, I am not against them on choosing such path for their lives. I realized I might have chosen a stray path against the mainstream choice back when I was graduating. But that doesn’t mean the mainstream is wrong.

My attention shifted to the corporate reality. Companies that I have worked with often nag about keeping millennials engaged and motivated in the workplace. One of the most common hypotheses they have is, the failure of keeping them engaged and motivated often end up in high employee turnovers.

Is it really the corporations fault? On not having able to engage with millennials? I hardly think so. The millennials we talked to also mentioned that, although they want to dive deep into the corporate world, it’s not their main goal at the first place. The main goal in the end is having their own businesses and crafts. The function of getting into the corporate world serves solely as a jump-start for their goal.

So, the reality of fresh graduates turns out to progress the way I see it, just not as straightforward as I thought it would be.
And I think the main problem is, big corporations simply try to motivate and engage millennials in ways that they think might have worked for people in the previous generations. While we, millennials, are self aware enough to know that the kind of motivation, benefit, and engagement that the companies give us, aren’t worth the long run. It doesn’t help us in achieving our dreams in making businesses, creations, or crafts.

But eventually, I would not say that the time-served by millennials in the corporate world is a waste of time for us. Millennials know it well, that the experience gained in doing 9-to-5 services in a cubicle is a well-needed discipline in building our future creations. What is asked often by millennials like me, in the end, is just how long do I need to do a 9-to-5 service? Is it a year? 2 years? Or maybe just enough to survive probation?

The challenge now is for big corporations to rethink their HR policy and work environment to enable more meaningful collaboration with millennials, each with their own dreams and aspirations. At first, I think it’s crucial for companies to acknowledge first, that millennials have deeper agenda than serving a 9-to-5 in cubicles while getting paid to do so.

In my utopian professional world, I want to imagine a work environment where there is common respect and understanding between a millennial and his/her employer about the dreams both want to achieve (this is probably why many millennials get the allure of startups, but that’s for another story). The failure of corporate engagements at the moments because they think of an ideal environment is for someone to dedicate their time fully to the organization’s goals alone. The room for inter-organization collaboration, for instance, haven’t really been the topic in the corporate world, let alone self-fulfilment. This is not the way millennials really think about their future.

This is why I think it’s crucial for corporations and millennials to have a more meaningful dialogues. I still believe there are ways to bridge the gaps, and I think it’s necessary that we start thinking on the way how. Because in the end, it’s for the sake of our own economy.