= Why making businesses should be millennials' cultural identity
:hp-alt-title: Making Businesses
:hp-tags: words, millennials

I believe we had shifted our way of life, especially about ideals on making a living, a little too far-flung from what our parents’ had taught us. We're the witness of student debt problems, unemployment, or even capitalism fallacy. We’re the first generation in the last decades who started thinking about skipping university and living life.

We emphasize more on to express our own unique individuality, and we seek out for more serendipity. We’re the first horizontal-minded generation, as we shaped the sharing economy. Our serendipitous, horizontal-life had been our cultural identity, and I think it’s time to make the best of it. How are we going to do that? I think we should make more businesses.

Millennials are the generation that went beyond the traditional sense of business. Businesses for us is more than just transfer of values, resources, supply chains, or profits. We think of business as one of the truest form of civilisation advancement. In philosophy, making businesses could be the noblest form of profession because it’s the only profession that tends to create platform, or medium where expertise, character, and networks grow. Enterpreneurism are now embedded in our dreams and life goals.

Making businesses means having that caregiving hands that groom magic out of series of value exchange between one party and another. In short, history had proven that businesses are one of the things that make the world go round. And guess what? Aren’t we in more advantageous position to do so at the moment?

Entrepreneurship, or making businesses is all about looking for that opportunity: a gap, somewhere inside this world’s value chain that you can tap into, create benefits, and deliver better results to the end of the line. It’s all about establishing that platform inside the chain that you can work over and over again, plant the seed of innovation, and reap the fruits of your labour.

Entrepreneurship itself had been a very alluring topic amongst our generation. Not because we’re naturally more savvy businessmen compared to our parents, and nor because we’re simply bored  and unmotivated to work somewhere in some established enterprises. The key difference in our generation is we put more emphasis on our own self expression or self enjoyment. We put value on the things we really, really love doing. This is really something that is truly millennial.

We express our unique individuality. We tend to be more inquisitive too in pursuing things of our interest. We study deeply the things that excite us, we enjoy ourselves so much doing those things,  we indulge in creating something out of it, and we tell others about it. We learn, we enjoy, we create, and we share. But we don’t want to stop there. The real appealing thing comes to us when we do more than just “tell others about it”. Then it is natural for us to think about monetizing what we do.

*The Passion-Driven Work as Millennials' Strength*

The idea of having work that are integrated or congruent with our object of passion is a relatively novel idea. This idea about work doesn't show up until the late 20th century, but rather made by people in the last decade. The growth of global economy had given us more opportunity, especially the young people, to be more expressive and able to indulge more with variety of interest and activities. Our wide range of interests and activities actually had given us possibilities which our previous generations didn’t really have.

Our devotion & inquisitiveness to our interests could be the answer to the hardest step of making a business: identifying that opportunity, or to point that gap somewhere inside the world’s value chain. When we decide to cash in on our passions, we put the responsibility to study deep about it, and putting efforts to make life a little better. In short, we would want to try making a more seamless value chain out of the things we love doing.  There’s nothing more emotionally-engaging than making our own living through the things we enjoy, right?

What’s more interesting about making business from the thing we enjoy most is, we’re actually re-shaping common knowledge about how businesses should be done. Business school class, and self-help books often taught us about the three stages of making businesses work: It’s all about making the right amount of profit, seek growth, and maintain sustainability. But the way we’re doing it, we tend to do it backwards. Our paradigm to make our passion-driven businesses work is: We want to make it sustainable first (because we want to do what we love as long as possible), we then seek growth (because we like it when more people joins in, and that’s why we often hear about startups “scaling up”), and then we seek out ways to maximise our profits.

When we make business out of our passions, we are able to do the whole thing a little differently than old businesses' wisdoms. Suddenly, what we see in the business world are people who started to see things emerging such as crowdfunding, kickstarter campaigns, and products with personalities. And it turns out, this new paradigm in making businesses work had made the world a lot better than we could ever imagine. Harvard Business Review, or The Economist had written about these kinds of emerging business model and startups more prominently than we could find in the last 10 years.

*The Imagined Future for Millennials' Business*

Self expression is the main drive for us to create something, that’s why we’re the generation of creation. Judging from this point of view, I think making business is one of the ways we can make a dent in the universe. And we should always remember the fact that we’re all naturals in it. It’s within our responsibilities.

Because we know it all too well about living as millennials, we understand each of our fellow millennial's struggle in making this happen. That's why we're more open for collaboration. We realized that the internet had given us democratized knowledge. We seek truthfulness in every event or stories (including marketing campaigns you throw at us). And we're not going to be interested about the things you sell as easily as the previous generations. We're more excited to hear why are you doing things, or selling things the way you are now. If you get our attention, we'd like to collaborate with you.

Advancement of civilisation had actually shaped us to the era where each and every one of us are like artisans and creators. We focus on our own selves, we self-reflect, we indulge in our interest, and we’re in charge of the world’s future economy. And by the power vested in us through social media, and global connectIvity, we're ready to take on the world economy by storm. I believe each of us are starting to shape their story at the moment. Most of us already figure out the thing they love doing, and we're going to make it big. Further than that, we're ready to make it personal. So that’s why, making business out of passion should be the biggest consequence of our generations’ cultural Identity.