= Life Lessons From Video Games
:hp-alt-title: Life Lessons From Video Games
:hp-tags: words, millennials

Many ’90s kids like us have experienced our own discomfort (if not hardship) dealing with video games. We remember the time we first got our hands on that small plastic controller of that 8-bit console. It was constant, near-impossible negotiations between us and our parents about how much time we should spend in front of the device.

Fast forward another 10 years, and I guarantee most of us still face the same problems. These sneaky habits we learned from avid video game use stuck with us while we were growing up. Little did our parents know playing these games could shape our lives in the most positive way imaginable. For me, it taught me a lot about life, and how to endure it.

I remember the times I played the crazily expansive MMORPG (Massive Multiplayer Online Role Playing Game) games. They stole most of my bedtime and studying time, and prevented me from doing my chores.

From the hack and slash types like “Diablo,” “Titan Quest” and “Dungeon Siege,” to the massive, multiplayer type like “The Old Republic,” and “World of Warcraft,” you name it, I played it.

These games hold a special place in my heart. I enjoyed the time spent skipping classes and being antisocial within the comfort of my bedroom playing these games. And I can say, after more than 10 years of experience, those days were worth it.

Here are five lessons I learned from playing video games all through childhood:

1. They taught me to be myself.

And being yourself DOES take effort. I am a late adopter of RPG games. I started playing them when most of my friends had made it halfway through the journey. When I started playing, all I did was copy whatever methods they had. If they said being a fire conjurer and warrior is the best thing to be, then so be it. What happened then? I sucked. Big time.

Eventually, I learned to carefully read character descriptions. I had to understand the best way to play, and the way I would like to play the battles and bosses. Something as simple as choosing a suitable character became an event because I had to take the time to really understand the way I played the games.

I had to understand how short-tempered I was to actually realize I’m not really the “support class” kind of person. I was more like a close encounter, melee, dual-wielding type of guy. By understanding that, I started a series of successful battles and fights. It took in-depth understanding of the way I react to the game before I could choose a suitable character/skill I wanted to use.

This applies to life. It takes effort to measure yourself and know yourself. This is a fundamental skill we need to have to win the battle that is life. It’s OK to indulge ourselves in many skills and possibilities, but at the end of the day, you’ll be forced to choose one or two things you want to spend your life doing. Life itself is all about that journey of self-discovery.

It took even more in-depth understanding to get used to the way I handle problems, and how I feel about facing adversity. We can’t go through life by copying other people’s coping mechanisms. It’s our job to pave our own path.

Self-discovery is the essential factor for us to recognize our full potential, our role in life. So, take your time.

2. You may know how to get things done, but you’re never better than other people.

OK, we’ve successfully understood each our battle type. We know every measure and skill necessary to play the game our own way. But we can never say we’re better than other players.

We can never say the Barbarian is better than the Paladin. We can never say the conqueror is better than the assassin, or the Jedi is better than the smuggler. We have to remember that our choices are made because it fits us. And at the end of the day, we need those other players in our party, too.

The same goes with life. We are wherever we are because we decided to be there; it fits us. It doesn’t necessarily go well with other people’s plans and ideas, but in the end, we’ll need them, too. We will never know what kind of dungeon raid we’ll get ourselves into in real life, and we don’t know what kind of surprises are waiting just around the corner.

And in some aspects of life, collaboration with the people who are different than you will be the only way to overcome an obstacle.

3. Life could always be harder.

Hardship comes naturally, especially in video games. The only way you can say your game is making progress, is by realizing your quest is becoming a lot longer, more strenuous and a lot more difficult than when you started.

That’s the whole point of playing the game in the first place. We want to progress, so we take on more advanced missions and quests, and we explore the map to have a better view of the world we live in.

If your life isn’t getting any harder than it was yesterday, then there’s something’s not right. You should always be challenging yourself. We need to constantly explore new opportunities in order to broaden our horizons, to have a bigger “map.” It will give us a better understanding of what makes the world go round, and will help us make more sense of it all.

4. Focus is key, but having a sidetracked life is not a sin.

It’s a necessity. The concept of “Main Quest” and “Side Quest” is quite common in MMORPG games. Main quests deal more with story line and class progression, while side quests act as extra missions with modest rewards. It seems like trivial tasks, but in the end, it’s worth enduring if you want to level up. Side quests prepare you for the face off with the main boss.

We are raised to focus our lives more on main goals and achievements. Our main quest in life is to go to school, graduate, have a steady job, find your passion and so on. But in the end, we do know that in order for us to grow, to gain experience, it’s the small side quests that matter.

It’s about the opportunity we take advantage of when we meet an old man walking down the street. It’s the damsel in distress we meet on the path we took back to your next quest. It’s the business opportunity handed over by a friend while we’re hanging out at the local bar. Give it a go, and it will help you later on your main quest.

5. Life should be cherished.

At the end of the game, you realize why you played in the first place. We all crave adventure. We’re craving some action, and we’re hungry for exploration.

We understand every failure is an opportunity to reformulate our strategy and upgrade our levels, and then we start again. Even if it took countless tries, we didn’t give up. We tried again and again until we earned that crown or legendary item.

Life is one epic MMORPG game. We’re required to measure ourselves, to decide our role, to select our skills, and develop them accordingly. We’re required to be in constant action, slashing enemies, overcoming adversities and defeating monsters beyond our wildest dreams. Our quest is to be, and to overcome. Our journey is to grow, and to level up. And in times of defeat, our job is to bounce back up and try again.

Life is one hell of a game, and it’s one you should be excited about. And at the end, you’ll feel all the troubles you face are worth the time and effort. The journey is worth the fun. And at the end of the journey, you’ll be proud to have lived life to the fullest.

Game on.