= On Life and Education
:hp-alt-title: an imaginary commencement address
:hp-tags: words

Hello Everyone.

Today is a fine day indeed. I stand here, feeling more than honored to be with you all. In midst of euphoria, joy, hope, and gladness, and also cluelessness and uncertainties, I am here to try to address some of the things I learned from life and my experience.

As we all know, there is no one-grand-strategy when it comes to life. We realize that the success story in the past, won't help much to navigate our future. We could still be hopeful, but we are at the very foundation, uncertain.

Let's forget a little bit about uncertainties. Let's enjoy this grandiose summer morning with laughter and hope. Let's fill today with optimism and a laid-back fun. Here I stand with you people, on this particularly fine day, to talk to you about three most important lesson I had received throughout my life. About education, and about life. I am here, to talk to you about: Commencement, Misdirections, and Resolution.

*Commencement*

You and me, we are one of the luckiest people on earth now. We live in a world where things had never been better. A little harder, yes, but never been better. The world as we know it has never been so optimistic and vibrant. We live now in time where opportunities and choices are so abundant, we have more of it than we have time.

Education, has been more relevant to people now. A lot of people have access to it, people are no longer afraid (or at least less afraid) to student loans or financing. We understand fully that education is more pivotal than ever. So we strive our society to have access to that.

Science has been more democratized now than previous years. And yet, we stand here on this event, as one of the luckiest person on earth, to have experience it all. Let us at first, be grateful of that fact, as we cherished our  drenched-in-agony years we had...

I graduated from university myself, around 30 years ago. I stand where you stand now, looking up to the world with anticipation and will as big as the world can offer me. There is no day like today, that speak to me as importantly as the day of commencement.

What is the core idea of commencement? Commencement is the start of the story. The first step of a thousand miles journey. Commencement, is indeed, be the scariest part of life. Yet it is unarguably the most important life event we may have taken in every journey we step into. It is the time when unjustified innocence face its trial, aspirations are challenged, and decisions must be made. It is the day when faith and willpower start to play their role. And today, of course, could be one of those days for you.

I start my career after my university graduation, with a choice to make. And it was not an easy one. Two roads emerge in the woods, as Robert Frost would have phrased it. And I took the road less traveled, and that had made all the difference.

It was full of regrets, victorious triumph, and celebrations. It doesn't matter what the outcomes are. What mattered was, I commenced myself into that path. I survived.

There is no recorded best practice to follow when it comes to life's commencement day. There are wisdom spoken to us from many sources about how to deal with commencement. The only way to deal with commencement, is to really take that first step, in any directions you think is available at the moment.

Commencement day, for me, is a time of faith. It has no room for indecisiveness and worry. No matter how you view today, no matter how uncertain you are in your future. It is just as important to understand that today is also one of the most important days of your life.

When you moved on from today, you are obliged to make bigger decisions for your life, and there is nothing better than that. Because life, is a series of commencement.

Constantly, try to do that leap of faith, hold true to the fact that to fall is the only way you will go. And you always have the chance to do so, beautifully. The point of commencement, is a reminder that life is full of leap-of-faiths. You jump again, after you survive another.

*Misdirections*

I remember myself, and lots of my peers when I graduate. We speak a lot about opportunities and chances that we can take. We talk a lot about hope and aspirations. We talk about the path we could now choose, thanks to the keys we obtained in classes and courses,

I was wrong. I should have never thought of my previous years within these walls as a journey to obtain keys and access to the wider worlds.

It took me years after to finally understand that what I was equipped with, are wrenches and bolts.

Education, knowledge, or a degree, are only tools. Hard-earned tools we obtained through discipline, papers, and deadlines. All that efforts we put to ourselves, endless sleepless nights, will not guarantee us to be master craftmans and creators. It is a mere training on to use those tools. A basic one.

And on a day like today, when we finally obtain those tools, the world no longer care on what you have on your walls. The world care more about what you can create with those tools. In fact, the world only care about what you can create. They do not care much about the tools you now have, or how you obtained them

On this day, it is important that we constantly ask ourselves on what are the things we want to create to the world. What are the things matter to us the most? And how can we start building that thing?

What then, are the things you could create with wrenches and bolts alone?

Maybe, we need hammers and nails too. And hammers and nails, are the things you obtain when you indulge on the things you love dwelling in.

Do not forget on the importance of hammer and nails. As it is also one of the things that will help you create things.

To believe that education is the key for a better living, is a misdirection. It is merely an enlarged opportunity to create one.

*Resolution*

Van Gogh, would never be the way he is, if he only painted A Starry Night throughout his life. Just like Da Vinci, would never be known if his notebook only contains one invention.

A baker, would not be called a baker if he baked only one batch of loaf. Just like any maker, would not be a maker if he make only one thing at a time. 

People could come up with many recipes on how to be good at something. Hard work, repetition, mastery, practice, discipline, and so on. It's an exhaustive list of self-help words you might find in your local bookstore. Willpower? That would be a great buzzword too. 

But however you frame it, whatever word you choose to be the foundation of great achievements, for me is resolution. A resolution well defined, is when you put huge amount of intention, decision, and commitment to do something, to constantly do it, or to create, and to constantly create. It's a form of mental determination to keep doing (or making) things you believe the world would need.

Keeping the spark of your creation alive, is just as important with the activity of creating itself. 

I stand here, looking at you eager young minds, with high hopes that you are the future creator of a better world. I stand here hoping that you will take part in the most important part of our civilization. I hope you would never stop creating things you believe in. With all the tools you had received today, tomorrow, and the days beyond.

Remember, that you are the master of your crafts..