= UX and LIterature
:hp-alt-title: an outsider's perspective of UX research and design
:hp-tags: words, research, UX, qualitative, 

### A little back story
Before I become a practitioner inside the UX field, I was previously not a person in design, software, tech, tech-startup, or anything that are close to the term. The term “UX Research” or “UX Design”, as much as they become the buzzword of the year, didn’t come to my attention until the last 12 months. I have spent my previous professional career working in qualitative research, doing research in many field like social research, cultural studies, and more specifically: developing marketing efforts for brands and companies in order to connect better with their consumers. It’s easy to find my name among the people working in consumer goods companies or business consultants.

Finally, by jumping in to work at a UX / CX Design firm, opened my journey towards understanding more about the world of UX, and also became the first turning point for me to get hands-on to UX processes.

Surprisingly, many of the discipline and efforts in doing UX research have many similarities with my previous experiences. Much of the UX discipline cross many of the qualitative research discipline I’ve learned. We shared similar way of thinking and mindset when trying to understand why people behave like they do, and we also put the same importance of that knowledge.

### UX: The General Idea
To me, the main idea of UX efforts are about integrating products (or services, or technology) into our day of life. UX can be seen as an effort to streamline a product’s disruption in entering the way we do our daily lives. Of course this term is a very broad definition, but let’s start from there.

The discipline of UX, in my opinion, begins at the question of “how will a product integrate with our daily conducts? How will it change the the way we do things before?”. The key main role of the product here is to transform our habit, our conduct, and the way we do our usual tasks, no matter how small.

Our role as UX designers or researchers in the business value chain, then, is to position that particular product as our client. And like any client, they have their own goal for us to tackle. It is within our duty to make sure that the product’s disruption in our daily lives, are as smooth as possible.

> _UX designers: We're the gatekeepers of innovation and disruption._

This approach sounds very similar in my previous line of work as a market researcher and brand builder. It is also within a market researcher’s duty to make sure that the brand they are working on can disrupt people’s habit and behavior, or to make sure that brands can understand its target consumers precisely so that they can really give the consumers a meaningful product and services.

In essence, to establish a meaningful experience for target consumers / users / customers through products and services, are quintessential works to both UX researcher and market researcher. If brand builders are the gatekeepers of stories, consumption, and habit, then UX designers have the same responsibility: to be the gatekeepers of product innovation and disruption.

### The common question for empathy
In doing UX or research approach, empathy to the target user is essential. And to achieve empath, we have to ask ourselves the most basic question: *“what is it like to be them?”*. Our task as researchers (or designers) eventually is to unearth a worldview in which our users / consumers live in.

Not only unearthing those worldviews, we are also obliged to live in them, understanding their way of thinking, what motivates them, how they live their lives, and eventually, how they are going to react when exposed to our products or services? We are required to be able to “read” people and their genuine reaction towards whatever offer we’re about to make for them.

Then, the question I’m often asked, what tools could be helpful for a UX researcher to have empathy? For me, a good appreciation of literature helps a lot…

### The importance of Steinbeck and Orwell in building empathy
There is no more robust tool for a UX researcher to understand users other than observation and storytelling.

The essence of being ourselves, our identities, or constellation of values are all embedded in, well, stories. The way we share our worldviews with the world, the way we share our political beliefs, our arguments, our experiences, are all in the form of stories. Stories as one of the main observation points for qualitative researchers, doesn’t only speak on individual levels, but also at cultural levels. The way societies and civilizations progress are by series of events happening, and retold in stories.

Unearthing stories surrounding the lives of the user comes to be a very important part of doing UX work. It is by making them to tell us their stories, we will be able to dive deep into their beliefs, values, and worldview. To position ourselves as UX researcher / designer, is like positioning ourselves like a documentary maker, a filmmaker, or a writer.

Think of John Steinbeck in “Of Mice and Men”. Think of how Steinbeck really put up a good narrative in helping us understand the lives and worries of plantation workers, farmers, or ranch workers. Or the best example that I can think of is George Orwell’s flawless observation and narrative in “Down and Out in Paris & London”. Orwell orchestrated a good example of observation and storytelling. He had succeeded in empathizing with waiters and chefs in a Parisian restaurants (or a beggar in London), understanding their motives, worries, and view of life, and retold that story and observation in impeccable narrative. What helped him doing so is the fact that he himself dived deep into the lives of those people (although unwillingly), and opened his eyes into the untold details of the people around him.

That’s why I believe that to be a good UX researcher / designer is for us to walk the Orwellian path of observation and storytelling. When we can dedicate our efforts truthfully, genuinely, in understanding our target users, we will be able to ask the right question, select the proper method, and also conduct it more effortlessly.

The question that we can ask ourselves, UX researchers / designers, is: Can we be the next Orwell or Steinbeck?