= The dream and the celebration of being young
:hp-alt-title: Letter to generation Z
:hp-tags: words, millennials, generation Z

_Forever is not enough,
Nothing can tear as apart
To be at your side (whenever, wherever)
To be in your heart (whenever, wherever)_
*~Destiny, By Homogenic*

I would like to dedicate this post to generation Z kids, whose coming of age are now spent in schools and universities. You're the real representation of the young up to this day, and there's nothing more I would like to say to you other than some thought-evoking piece, and means for self reflection. I believe adolescence years, or university years are the most pivotal moment someone could experience. I've passed that moment long ago, but the memory remains.

When we're young enough to escape the dread of adulthood, but old enough to practice responsibilities and exercise freedom, there is one universal longing that each of us may face. This universal longing, revealed to me through a dream, is what I am going to talk about in these threaded letters...

== The dream
It was one autumn afternoon. I was just about to leave the last class of the semester. I grab my pullover jacket as I walked outside the university building. The wind was pretty much chilly, but a comfortable chill. With occasional gust rushing down my face, I could say that it is a lovely afternoon somehow. The campus was just finishing its last day of semester. The student bodies and fraternity houses are arranging a communal party in celebration of the end of semester. Though the ambience of the scene was pretty laid back, I can sense the exhilaration and relief in the people around me. They were smiling more, laughing more, and I can't help but to share the same spark of joy.

A friend (whom I've never saw in real life) walked towards me, asking "are you going to the concert tonight?".
"Yeah sure.", I replied.  We walked together around the campus complex, talking about the frolic we encounter throughout the semester. The small talks we made assured me that me and him are long-time pals. We talked a lot about the things I never remember having in  real life. But nevertheless, it was a very enjoyable talk.

It was a peculiar setting, seeing the people present at the dream. Much of the people I've met and talked to are the people I did not meet until later in my professional years after graduating. There's this guy whom I haven't seen since I graduated in real life. There's also my ex-coworker who did not attend the same university as I do. There's also an old high school friend I never talk to. There's my coach in the university marching band, planning to get drunk in the library's basement with his close friend. Why am I seeing them in this dream? Attending the same university and sharing the same scene of youth utopia, I don't know for sure. They're simply there.

The scene, the people, keep changing throughout the day. From a laid-back party scene iin one of the school cafetaria, a concert performed by Homogenic, up until it was a little bit past midnight. We were planning to go back home from our evening walks. So I said goodbye to everyone I met along the way. It was at this moment I opened my eyes and realized that it was a dream. A vivid and strange one indeed.

== The train of thought that follows
I'm no psychoanalyst. I don't do well in interpreting dreams and its meanings, but I do understand that dreams serve as fragments of abstract images from our previous experiences. It also reveals to us our deepest longings. I contemplated deeply, trying to make sense of what I just saw.

I'm not good at making an accurate sense of that dream, but some things are definitely clear to me. First, I miss my adolescence years. It's a time of opportunities and experimentations. It's a time of deep learning in which I regretted skipping some opportunities of taking up life's lesson. And secondly, it reveals to me that if I am ever going to repeat that phase of my life, I would rather spend it with the friends I make today. Not the friends that I made back then. Clearly, I realized that there are people whom I currently wish I grew up together with.

My dream about the adolescence years, revealed to me my inner longing of wanting to experience once again, the togetherness of making a life-shaping journey, a longing for making a long-term connection shaped by common experience and camaraderie with the people who matters most to me today.

These are good insights for me. It reminds me of the things that define our youth. I believe the longing we experience when we were young, revealed to me in a dream, are a universal longing present in all of us.

I tried to pin down the main things we, and every young people around us long for. And I could come up with a few things. And these things, I believe, are the things that every young people should be able to do.

If you're currently young enough to relate to my words, I would recommend you live your life doing these things. It's for your own good.

*Exploring curiosities*
Exploring curiosities are one of the main perks of youth. It's a chance for you to wonder and wander. To ask questions, to be inquisitive, and be goddamn curious about anything. It's a natural calling for young people, and should be taken seriously. If some things are able to get you wondering, then it's worth to think about seriously. In the end, what is youth if it's not a constant child-like wonder?

I always believe that adolescence should serve as your second childhood. It's the peak time of psychological development, and emotional intelligence. Back when you were five, you learn how to move that little hands of yours, how to walk and move efficiently, how to operate a computer, and so on. But when you're in adolescence, it's when you learn to feel and to think. You will experience the yearning for philosophy and reason. And there is no excuse in not exercising those things. Be curious, be curious.

*Making small experimentations*
Experiment on all things. Try things. Experience new stuff! Experience failure! Experience heartbreak! Try photography! Learn to do yo-yo tricks! Try a new romance! Just try! You will never find better timing to try all of these stuff. It's a time for you to challenge yourself fairly and openly, because nobody gives a damn on what you can do at the first place. If you think it's doable, then you should probably try it.

The value of making small experimentations goes a long way in life. Nobody regret the things they did more than they regret the things they didn't do. Making small experimentations are like investing your time, resources, thoughts, and experiences on things that may come up later in life.

*Have small celebrations. In fact, celebrate everything*
I mean it. Celebrate everything. You passed that test? Celebrate it! Grab some beer and go out with friends. You finally get that pretty girl's number in physics class? Celebrate it. For every milestone you set for your small life experiments, celebrate it. Celebrate both success and failures. Have fun.

I think hollywood movies get it right when it comes to college or university life. Its depiction of constant partying and having fun are indeed essential. We just need to frame it on a more productive terms. To celebrate everything, means to accept everything life had thrown at you. There is no better times to learn other than your college life. Trust me.

*Learn to be there for others, in times of need*
You are not alone. You're part of a communal growing-up rites of passage with the people around you. You share the same responsibility on making those small life-experiments. You are the only people accessible to your friends when they want to talk about their curiosities. You are the one they would turn to in moments of small celebrations. In essence, the things you want to do in your youth, you will never experience it alone. You will share that journey with your red-haired flat-mate, you'll share that with that dude who helped you ace mechatronics.

And the least you can do is simply by being there for other people. It's important for you to understand that each and everyone around you now are longing to do all of those things I wrote. It's indeed a shared experience, and trust me when I say that the kind of people you associate yourself at this particular time, in your youth, will determine the kind of people you become.