= Gen-Y, The Paradox Of Abundance And Why We Should Read More History


There's nothing Gen-Y is more proud of than being a part of Gen-Y. Let's recap our lives a little: We've seen faster-growing societal development than most generations have. It took us probably less than a decade to see the world changes in front of our eyes.

We're the lucky generation, and we are accustomed to change. We're the generation that is spoon-fed uncertainties and guided by cluelessness.

We're the generation whose 20-somethings have the hardest time making sense of life, yet we're also the generation that is most self-absorbed, self-reflective and the most self-contained.

We're the generation that faces the constant friction between society's expectations and our inner values. We're the generation of earned substance.

We're the generation that's the most rebellious against the status quo. We speak up to our parents just because. We fight with them and we learn to make our own decisions.

On that point, it's obvious to see that the future of the world is within our reach. It's our responsibility to drive ourselves and our society to a better world than we all imagined.

Information is a single click away, a touch away or even a glance away. Self-enrichment is no longer a question of access, but a question of mere determination. The treasures and riches of the world are now hiding beneath our plain sight.

But the downside is that we do realize we're a generation with an attention span shorter than that of Dory the fish (and we are a generation that gets that reference). Our generation is often considered to be the generation of historical oblivion.

Previous generations often complain about how easy it is now to have access to vast array of information, yet we pretty much don't care about using it. The beginning of a borderless society is not that far on the horizon, yet we're hardly prepared.

Aren't we though? We could list reasons and arguments in defense of those accusations, but maybe we'll save it for another story. Now, if we dig deeper under that accusation, maybe we'll be able to ask, are we really doing the right thing at all?

Are we really growing how we're supposed to grow? Are we restless enough in trying to shape society how it's meant to be shaped? Could history or past wisdom really get us somewhere?

I could agree that often, what's missing from our generation is our uneasiness, curiosity and inquisitiveness in the midst of mediocrity and straight trajectories.

We're often trapped by dwelling inside our comfort zones. We get too focused on realizing that the world is indeed better than previous times, so we settle. But, we forget that the world is changing, and fast.

I've been lucky enough to be in an industry and social environment where things like these are the daily topics of conversation between peers and fellow professionals.

As me and my peers strive to move forward in our business, or even try to set our place within the society, we realize that advancement is difficult to accomplish. And sadly, we're who gets in our own way.

I've heard a lot of business practitioners out there complaining about the overall attitude of Generation-Y, which they define as the so-called "paradox of abundance."

The paradox of abundance goes like this: Think of you being seated in a buffet restaurant where you can have everything you could ever imagine, served on the table in front of you. Yes, we could have it all; unfortunately what we don't have is the appetite.

Think of all the things we could get so easily now in life. Information, skills and collaboration are right under our noses, and probably just a data-plan away.

Yet we feed our short attention spans with disproportionate amounts of endless cat videos and a dresses of blue or gold.

What are we looking for in life? Are we busy trying to make ourselves look cool with our wide range of activities? Are we busy feeding our interest with entertaining-yet-mind-dulling gossip we love to share during our lunch conversations?

Are we really so deprived of ideas to discuss about in our spare time that we now seek small things to talk about over one-line messages?

Are we busy enough expressing ourselves with brands and products we see making their way into the furthest corner of the world?

Deep inside, I am sure, despite all these distractions and lack of focus, we'll get it right some day or somehow. Cluelessness and distractions are natural parts of a Generation-Yer's life.

Maybe we need that cluelessness to take our generation into its ideal full form in society.

Maybe we need those distractions to give us more serendipity in life. It's not wrong to slow down a little, seek out information and make sense of those wisdoms of our past so we could be more sensitive in determining our own life's success stories. Eventually though, isn't there nothing new under the sun?

The industrial revolution had shaped our society into the capitalist force it is today, but the world is moving toward the borderless society through technology.

Start-ups and business incubators made their way, creating things we've never seen before, yet sending us back into the old artisan, pre-industrial economic era.

We dream of making the world free from hunger. We want to make the planet more habitable, and we want to leave a better place for our children, just like the hippies from the mid-60s.

If we plunge ourselves a little bit more into the stories of the past, or if we study our history in a little more perseverant manner, maybe we could make sense of the future.

We do realize, though, our life context expanded into unknown realms and our narratives do not evolve that much across decades or centuries. Our experiences have already been written about.

So, why don't we start being a little less oblivious and plunge ourselves into the past? Maybe it'll help bring about the utopian society about which we only previously dreamed.

Maybe we should humble ourselves once in a while and listen to what those old folks are trying to say.

For us to really change the world, maybe it's time we read more books, be a little more curious be more inquisitive and to cherish our time by respecting what our forefathers had envisioned back then. Maybe after that, we'll be ready to put up with our current challenges to make this world a better place.