= The stoic's journal
:published_at: 2018-01-01
:hp-alt-title: a late night thought
:hp-tags: words

Just fifteen minutes towards midnight. I lay in my bed for hours now, trying to shut down my brain for a good night sleep. But my consciousness seem to have another idea. I can’t turn those thoughts off. Those train of random thoughts and event running around like race horses on steroids.

My existential being betraying my body. The harder I close my eyes, the more the images in my head explode with colors. The harder I put effort to shut my mind down, the more vivid those questions arise. Magnificent.

I thought about my days lately. It wasn’t that much fun, but it’s normal. It’s just the way it is. Fun days are overrated. To hope that everyday is filled with joy, enjoyment of work, or fulfilling achievement is so hollywood like. Something you could only find in sitcoms or romcoms. No, life is just as normal as it should be. Like rainy seasons, it happens in certain time of year. Rain is there, it will pour. We predict rain, we prepare ourselves for it. Just like we should prepare our days with betrayal, irony, disappointment. It’s all there, a natural change of seasons…

What are dreams or plans? What significance it brings to our psyche? What sense of safety do they evoke in us? Do they even work at all, I wonder… Why do we hope for good things to happen? When the meaning of life is to endure and to walk on? I have strayed upon the path of comfort and security, for it has robbed me from freedom and simplicity.

The people who are close to us, have the tendency to stab us in the back of our head. They will disappoint, they will kill our characters, they will rob us from our dignity. 

Our lovers will stray, or they will doom us to loneliness. They will run around with our fragile hearts, tossing playfully with trials and experiments. They will sometimes put ours aside, making room for other hearts to be tossed and played around. In its most optimistic scenario, they will try to cage ourselves within the boundaries of institution and beliefs, trying to make the world go round with the word “us” as the navel of universe.

Stray, oh stray, we will all be. 

But do all of those things matter? Aren’t they just a part of life? And don’t we all have control over our ways? We could say no, we could turn back,  we could abandon, and we could just walk on. It is the essence of life. A journey of decisions and steps taken, but never to turn back. It is a journey of detours and closed opportunities, but never we can stop.

I believed, once in my life, that I am free. Freer than i thought I am. 

With freedom comes the utmost consequence, and that is choice. Oh the irony of choice. The byproduct of freedom that also robs us from freedom itself. We are freer than we could ever thought, but we are never for once free from regrets and consequences. Then what really lies in the definition of freedom? What lie does the word contains, which fools ourselves to chase the mirage of happiness at the end of the rainbow. Rainbows, then, never really touch the ground.

The world revolves around its axis. Along with its ever changing seasons and storms. We are never free. We are doomed with our choices, with clocks ticking awaiting for us to make one, tick-tock, tick-tock. And life holds its utmost reward, for people who sticks to their choices…

We are all, part of life’s journey. We are part of other people’s choices. We are free, but never in ways we thought we were…We are free to adapt and adjust. The only essence of freedom we were given, at the consequence of our choices. We are at the very end, free to associate, to disassociate ourselves with the things that matter. We are free to define what, and how, things or people matter to us. And we constantly abide to that rule, that we will always have to decide, decide, decide… We are free to decide, but we should continuously, vigorously, decide, decide, and decide… For decisions, is the only way we step forward. Holding ground, is not life’s way. 

Oh the sin of memories! How it shackles our ankles from moving forward. How sentimental the images we once had in our heads, that stray us from the path we wanted to walk upon. Oh deadly memories, thou shall walk me in circles! Thou art like cyanide. A poison of life. Memories, are stories. It soothes, it’s retold. It detaches us. It disconnects, it distorts. Is the essence of being free to live, lies within us being free from our memories? 

Oh lies, lies, and lies… If only lies are a person, for me to hold its neck with my bare hands. Or should I just be blind from its frolic and amusement? Then what is the cost of holding a grudge towards it? How will it benefit me, holding the truth for the sake of politeness… 

It rains outside. Rainy days happen. It’s a sign of life. Just like disappointment, betrayal, or hate. It’s a change of seasons. We are never going to be free from its pouring over our heads. And I assure myself, mankind are made to get through such adversities. We are always at the power to endure. And we will be okay… 

“We will be okay… “

I drift away to darkness. I fall asleep under that blissful spell…