= The (post)Modern Pilgrimage


> I am not naturally expressive when it comes to certain topics, especially topics about religion and faiths. I understood that faiths and religion should be a very personal matter. It should governs your relationship and your relationship only with the supreme being / the universe / with people around you. Yet, I hope that the things I wrote below, could also be a voice for more people in distress…

I am a Moslem. I am not born a moslem, I am not an indoctrinated moslem. I am one of the few lucky people in Indonesia who are nurtured in multicultural family, and I am more than lucky to be a moslem by choice. Not by doctrine. 

I embrace the teachings of Islam. But I am also one of the growing number of Millennials who are starting to question their faiths.

No, I am not questioning about the relevance or truth behind the holy book. I am not questioning the true historical nature of the prophet or the holy men before me. I embrace the teaching as my philosophy of life, and in fact, I hold dear to its values.

I currently stop to publicly announce my faith, or to publicly do my rituals. I don’t publicly announce whether I still do my prayers or not. I stopped going to Friday prayers not because I don’t believe in its importance, but I rather not endorse it the way it’s conducted in my local community.

Long story short, I am simply questioning the real reason my local society is currently adopting this faith.

*Local Stories…*

In a country which have the combination of having the largest moslem population on earth, and also having the widest gap between modern and traditional societies, it is well understood that Islam had embed itself on majority of our social construct for ages. 

In social context, the history of Islam in Indonesia had not been free from political agendas, propaganda, indoctrinations, and also local adaptations. Although Indonesia by design isn’t a moslem country, the teachings of Islam had arguably infiltrate most of our sociocultural values upon which a perceived good functioning society stands for. It is practised, endorsed, not for mere personal governance, but also becomes a measurement for good-functioning society.

Unlike many high-profile countries, which ground its societal standing based on a deliberate focus on humanitarian rights, this country seem to have customised its social consuetude based on mix of local common sense and literal religion repercussions.

Although some local Islamic societies do practice a modern and progressive approach towards its understanding of teachings, some other societies still think that Allah (our God) is a totalitarian dictatorship, in which His words are to be practised as it is, word by word. Or else, suffer the consequences.

This fact alone had jeopardized our society by segmenting the faith itself into many sets of localities based on each local interpretations. The verse of the holy book are universal and in uniform. Some believers (if not most), are simply lost in translations…

There are no longer universal Islam. It’s only a postmodernist faith with (almost) no grand narrative, segmented by glitch in how we communicate. The dream to unite all men under the “same faith” now sounds like an oxymoron.

*Juxtaposing Progress and Anachronistic Changes*

The development of world civilizations could not be avoided. Progress is the intermediary cause of change in developing-countries like Indonesia. Often times, changes were never smooth across societies. And here, cultural conflicts seemed to be the most prominent shades in these changes.

Cultural conflicts usually happen in these scenarios: Modern society had empowered certain religion-powered-societies, which enable them to rise in power, or to have firmer stand within our social construct. The stronger the forces of modernizations, the tougher they stand to the values they once believed in. It’s part of the science of human nature. The stronger you pushed our walls, the tighter we build our barricade.

Some other societies could answer to the rising social complexities with ambivalence between literal back-to-the-book approach, while superficially adapting themselves to be in the centre of the inflicted social changes. This is the most perplexing communities to face. We see no philosophical ground on both end of the story. Ambivalence at its finest.

To illustrate, let’s imagine the following case: In modern times, when world civilisation had made way to diplomacy and multicultural cohabitation, it seems anachronistic to go to Friday prayer and listen to the sermon about heaven and hell, and whether it’s halal or not to kill your non-believer neighbour…. Unfortunately, 9 out of 10 sermon here, that’s what you’ll get. Are we still living in the age of war against the infidels?

How could that be? I guess that’s what happened when you juxtapose modern context with ancient wisdom without having to go through the entire understanding process. The current mainstream Indonesian moslem society that I know around me, failed miserably in providing the Islam that I see fit: A faith of critical judgement, compassionate values, and contextual rules.

*Coping Mechanism*

I guess these reasons are the cause being a moslem in this country is hard enough, and it’s understandable why more and more young people tend to lose their faiths. More and more people  like me are questioning the true measure of well-functioning society. How can we not? We are so used to face a moral dilemma as follows: 

> To be a good citizen in my society, I should show myself practising good routines of my religion, I should go to Friday prayers, for instance.
In my friday prayers, I am told that it’s okay to hate your non-believers neighbour. Does that made me a good moslem? Does that make me a good individual in the face of society?

> The people around me, tend to preach about sins and good deeds. Life and deeds are zero sum game, and God is an accountant…. Wait… What?!! 

> Is it really true, that showing that I’m good at MY religion DOES make me a good functioning citizen of my society? Does that make me a hypocrite, or does that make me presentable?

Young members of modern society could challenge these views in their daily basis. Their coping mechanism resort to their understanding of religion the way they see fit. This article, whether it’s true or not, relevant or not, is simply just a coping mechanism. And the debate that goes along with these kinds of expressions, are also coping mechanisms.

Furthermore, I don’t think people who announce that they’re starting to question their faiths should be addressed to, or considered a threat. We all know that these people are results of their own coping mechanism towards local interpretations of values, unfit social construct, multi-faceted exposures, and self expression… The problem lies more in the environmental aspect of the practised religion, not on the beholder of faith.

*Where now?*

Well, the dream to engage more people like me to be more spiritual and religious, is to put more sense on how religion itself is used to govern society. 

No, it’s not going to Friday prayers that will make you a good moslem. It’s not having to fast for 29 days that will make you a good moslem. It’s by understanding why such rules are born in its times, and understanding a holistic impact on our society that will make you a good moslem. It’s by embracing the critical, compassionate, and contextual aspect of the religion, then you could be a good moslem.

It’s to have a firmer stand about why you’re doing the rituals to your faith. No, don’t say that because the book says so. Don’t say that I’ll go to hell if I don’t comply. We need more tangible experience regarding the way we do our faiths. Not just some blind propaganda and fear-induced repercussions….

Some societies had succeed, but I guess the majority of people haven’t follow through…

Where do you stand?