= In faith of digital
:published_at: 2018-01-31
:hp-alt-title: the digital blind faith
:hp-tags: words, research, business

*Story of Startups and Technology*

Startups equal technology. These are the things millennials all over the world start talking about. From a coworking space in the western side of Bali, up to a hip San Fransisco district called silicon valley. It's been used a lot, the word association seems stickier than a gum on your hair.

But what's a startup, essentially?

A business model experimentation. Yeah, that's the word I'll use. It's a bunch of people bonded in a legal bond called a "company", trying out new stuff to experiment a business model that can reach a large market in just a few years (and this is fast for a scaled-up multinational company, if they make it). Trying to reach that amount of market size (or some people say "traction"), is indeed challenging. Resources need to be burned in order to create infrastructure that are capable of sustaining that (hopefully) big market size. And this is why money and capital matters.

And talking about "infrastructure", it's no debate, that technology (thanks to internet, interconnectivity, smartphones, and cheaper data plan) is indeed one of the most effective way to make sure the company "gain traction". I said one of the most effective because somehow I don't believe it's the only way. Especially if you're sitting in a country called Indonesia. One of the largest third world country which growth now higher than South Korea, thanks to its micro segment.

*Leveraging current practices*

So what's going on there? Well, let's study the exhibits. We all know that company like Go-Jek soar and made it up to the New York headlines a couple of years ago. The success story about creating a digital product to leverage an ongoing practice of motorcycle taxis took the market by storm, and suddenly now people in big urban city like Jakarta now depend their daily lives to this services.

At the surface level, yes, we know this company leverage technology and online. But I think the more important matter we should look is the way the practice of motorcycle taxis work as an ongoing practice. The power of that company is actually on the established practice of the motorcycle taxis. The technology is only leveraged to make sure that the entire customer process of getting a motorcycle taxi service is paved smoother.

The business is genius, because it acknowledge a behavior that existed, and the technology just scales up the entire practices. Copy it to other region, and there you have it. Big success.

*Realities, realities*

Position yourself as a business consultant that deals with people getting hyped up with technology and digital products. Now you're in my position.

The work is of course, damn interesting. Always a new way to experiment new models and approach in trying to reach a scalable market in short time. The goal is to create a pathway for consumers to use your products, whatever it is, and gain something out of it for them to happily use it again. You're improving people's lives here. You're making an impact. Do I sound like a millennial already?

But it turns out, sometimes, this goal is hard to achieve. Why? Let me get there soon.

The problem here is just I've seen a lot of people trying to create products or a solution just for the sake of creating a solution. And they're doing so, creating these solutions for problems that don't exist in the first place. And why do I start to feel like this is a generational problem?

What happened is, people forget about the current practices. Especially the ones the target consumer is doing. One of my headaches working with young startup people now is they don't really care about the lives of their users. Their focus is more on the things they imagine the users have, without having to check whether that's a problem the user really have. Talk about failure to do market validation here. Trying to create food delivery service for bicycle couriers. Where do you think we live? China?

The other thing is, sometimes I face people who forget that not every demographic of the user are ready for digital. Yes, I KNOW that digitalization is inevitable somehow. The future lies in digital and big data. But when can we learn that not all, I repeat, NOT ALL demographics are ready for this? At least if you create a digital product to reach this unready market, why don't we create a roadmap instead of a "digital product"?

I think, this is the most difficult part of the job. Not about creating opportunities, but having to face people whose ideologies in creating a startup business went against the fundamental of creating a user-centric product. When they're creating things that simply solve a problem that doesn't exist, the worse part of the job is actually having to tell people about it in their faces.

*Next step forward*

If there is one design question I'd like to solve, I think it would be "How might we make startup creator (clients) to be more grounded in creating their product plan (or simply to be smarter)". Sorry man. I need to say it sometimes. Clients could be just as stupid as an ungrounded freshman out of some fucked-up business school in rural Mordor.

But then again, I don't blame them. The changes in this world, is just too damn fast, I presume. We've seen development of business and innovation at a rate that is faster than traditionally schooled, well-educated, middleclassmen can perceive. Who knows what are the things possible achieving in the near future. We're simply trying our best to navigate the waters of innovation steadily, with all the best knowledge we have. The future is still uncharted, and we try our best to make sense of the seas ahead based on our previous wisdoms and practices.

I think it's important for us, whatever business we are in, to have a reboot at our understanding on how to create and make business work. Our understanding of business wisdom needs to change, and it needs to be the central point in our endeavor. No, your skills and experience as a back (or front) end developer won't do you any good, won't help you make good products, if you can't focus yourself on the reality of your potential users, or if you can't admit openly that your hypothesis is entirely off.

Digital platforms are only tools. Enablers. Enablers for people to achieve something, something they are familiar of. And to understand their main motive and goals is central in creating a digital product that works seamlessly. This understanding of the end user should be the quintessence of a design discipline. And I do think we should start from there.

Don't be an overly hyped up startup person. Startups are costly and expensive to develop. It takes resilience and hardwork, and not forgetting good timing. It takes passion and a belief that products are solving user's problems. But sometimes, fundamentally, it does takes a good observation skills and a bit of intelligence to make it work. Groom some.