= Why am I here, and not there. An existential wonder
:hp-alt-title: an existential wonder
:hp-tags: words, life

I’m no writer, no matter how much I’d like myself be. But I’m sure that there will comes a time when you’re old or experienced enough, you’ll find it hard to express your thoughts in a piece of writing containing only a few paragraphs.

I often envy those who spent their times constantly pouring their ideas into words, consistently, so that it’s easy for other people to consume the overall thoughts in small chunks.

I find it hard to write all the things I have in my head that can take up only a few minutes to write, but I’d like to try to sum it all in one question. That question would be “Why am I here, and not there?”

No, it’s not that I’m not being grateful of where I am at the moment. I can’t express better gratitude of where I am right now. A sense of purpose, a good career, and an expertise I can be proud of. Moreover, having myself able to commit to certain lifestyle of simplicity had given me more freedom than I could never imagined I can have.

Years ago, I might want to be able to live life in certain kind of grandiose. I could have a life somewhere with a nice weather, have a house with certain interior style, and commit my pastime activities restoring old classic cars. The allure of living such a life is indeed still there. But now I think I manage to balance that ambition with a more purposeful gratitude. Life has been great. There, I said it… It couldn’t be any better than this.

But, it’s funny to realise, even when you have that spirit, the question never fully went away. “Why am I here, and not there?”

As existential it may sounds, I would not let the question linger to be a kind of sorrow. I’d like to emphasise that question in a more positive, and cheerful way: I’d like to think of it, as a sign of longing of growth.

It took a degree of self-acceptance, I guess, to be able to say that. Self acceptance of your overall journey, and how life brought you to where you are. An acceptance of the way life put us in hardships we hate, but we finally overcome.

No, I’m no hypocrite. I hated those difficult times. Sometimes it still gets on my nerves. And it’s normal. Most of the time in life, we hated those difficult times so hard that it shrouds the triumph of overcoming them. And I’d like to say that it’s normal. The time of total appreciation to those triumphant moments, probably isn’t now. Maybe later. So let’s accept the fact that we CAN hate some aspects of our lives too. It’s normal.

---

There are two times in our life, when we became very adept in writing about our own experiences. One, is when bad things hit hard and we are forced to navigate the rough current. We became very sensitive to stressors and external triggers, that we begin to internalise everything into our consciousness. Two, is when emptiness strikes. We begin to look for something we deem essential for survival. Suddenly we swim deeper into our memories and consciousness, looking for traces of life we might left scattered behind us.

In both condition, I think the essential question sums our discontent, or sums the story premise very well. “Why am I here, and not there?” . In emptiness, or sorrow.

---

What to do? What to do when the question arise? I have no direct answer to that. And I think none of us have the answer to that question. I realise that the more we wanted to answer that question, the more confused we will be. I mean, let’s be honest. The majority of cause we can think of about the things (good and bad) that had happened to us, happened in the past, and it’s just pointless to be pointing fingers at something we can’t change.

Shall we point fingers to things that are happening in the present then? Well, what are the things within our confined time-space continuum, that are really within our reach? I mean, are other people’s intention within our reach as well?

The more we think about it, the more we’ll start to realise that the whole idea about thinking of it is just pointless.

But looking back, bad things and good things aside, in good times, emptiness, or sorrow, we lived. We got through yesterday. If we can get by today, I think it’s good enough. We might not fully outside of our soul prison yet. We might be aware that we’re not fully outside our hardship yet. But we lived. As cliche as it sounds, it always comes back to me, to say that we’re destined to get things figured out.

The key is not about being able to answer the question of “Why am I here, and not there?”, but to accept that the question is omnipresent. It’s everywhere. It’s there every time. It’s just, there. A consequence of consciousness?

---

“What are you up to?” someone asked me

“Thinking, wondering…” I replied

“About what?”

“Wondering why am I here, and not there, I’m not sure.” I said

“How are you feeling”

> I’m okay, not okay. 
> I am fine, I am shattered.
> I am here, and everywhere.
> Everything, is just as it should be.