= On Qualitative Research - An Artisanal Perspective
:hp-alt-title: an artisanal perspective
:hp-tags: words, qualitative, research

A few years ago I remember doing research in one of the rural areas in Bali. The subject of my research back then is a local artisan. A wood sculptor. A man in his mid 50s, and had decades of experience in his craft. He's one of the best among other sculptor in the village, as he is often looked up by the younger craftsmen. 

It was one of the most interesting research projects I have done. There are lots of learnings and framework for understanding at play. But what makes it most memorable, is the way this particular exchange with this artisan shaped my research philosophy. 

I talked with him casually while he's still doing his work. Sculpting a large wood block that half resembles Ganesh, the Hindu god of knowledge. While I watch him working his tools on the wood's surface, we talked about knowledge. A transfer of collective wisdom that shaped my understanding about what I do - research.

### On tools
> "These hammers and chisels, they are meaningful, but only to certain point in your craft… There is no point on having all the new ones, the round ones, the sharp ones, the ones with the custom-floral patterns. It adds up to your process. But mostly, it adds up to your ego."

He said that after I made a remark about the crooked, half-split chisel he kept using. 

In his point of view, I get it. The hammers, sets of chisels do serve different purposes. Some sculptors invested a lot to obtain such tools, in hopes to make their craft more refined, and easy to work with. But it's really easy for one to be distracted by those "new features and abilities". 

I mean, it is clearly possible that in his world, there are lots of people trying to sell better tools, better chisels, better wood-scraper to him. Even the art market where he supplied his work, sell those tools as well. I asked about his tools, and it is to my surprise, that he only have a few. Probably just a couple of hammers, and 3 types of chisels.
And yet, he crafted magnificent, and well-detailed sculpting, big and small.

That's what I learned about tools. A vast array of tools in our toolbox may help us to refine our work. But it's important to remember that we should not be distracted by it. A sculptor who focuses solely on obtaining better tools, believing that it will increase his productivity, or ability, often got stuck just at that. His faith and attention now is narrowed to the tools, forgetting the first reason he's there in the first place: Sculpting, or creating work of arts. 

That goes the same with research. I often met lots of researchers who are easily swayed into collecting methodologies or literature, believing that it adds up to their understanding and ability of doing research. The discussion revolves around obtaining or using the most perfect tools and methods, which one to use and when to use, but forgetting the spirit of doing research in the first place. 

Like an artist's work, tools help. Tools or literatures may be collected, and praised, or debated. But the main purpose of those tools, they are there to be tried, to be familiarized, to be used. It was the artist, the holder of those tools who have the final judgement whether or not: the tools fit with his habit, the tools fit with the medium, or whether the tools fit with the artist's vision.

Research methods, toolkits, and sandboxes are just like a sculptor's hammers and chisels. The point of it is not to debate or to collect it, but to use it, to familiarize ourselves with it, to fully support us in our research vision. But eventually, most of the time, it's more about working with what we have at the first place. Know what you have, and more forward. Remember: Limitation of tools shouldn't stop you on creating high quality research.

### On vision and execution
> "Yes, before I start, I usually imagine how a sculpting would look like in the end, but to blindly believe that it should be exactly the way we imagined is sometimes a folly."

In every art discipline, be it music, visual arts, or performance arts, there are at least three aspects that are the main focus: Conception, Execution, and Perception. 
Conception is the realm of initial ideas and vision. A production of art work is the result of a conception process. A creative process that usually involve imagination, interpretation of initial stimuli. The ideal form of an art work, a world without constraints. 

The big chunk of the effort, is always on the execution phase. Execution is the main determinant of how a concept is brought to life. The key is to discover and define constraints. Can the ideal concept that an artist once imagined can be executed? Does the medium allow such form to be created? Do the tools serve an adequate capability? The execution phase is all about constraints. It's the things that comes up when the work has been started. The surprises, and the things unprepared for.

Even after an art form is successfully produced, there is no guarantee that the art is interpreted the same way by its audience. This is called perception. Eventually, an artist must give some room for the audience perception. Allowing interpretation that could probably unaligned with our initial conception. 

Research work, just like any other art form, also went through those three main steps. Conception, Execution, and eventually, perception. We conceived research ideas based on business goals, which we interpreted to be research question. Interpretation of the business goals could also depends on the "artist" (the researchers). It depends a lot on our subjective understanding of how the business works.

Execution is how we translate research conceptions and ideal into smaller chunks of actionable steps. This is the realm after, and beyond the research plan you wrote on your Google docs. The key is the same, to discover constraints in data collection, and to define meaningful data source. Focus on execution also means putting your effort on project management, interview techniques, and finding the best frameworks for meaningful analysis. Often the big chunk of doing research lies in the execution phase. It's where previous understanding of research are put into play. It's where experience matters, but also where it shapes your experience.

Lastly, it made sense for a researcher to leave room for perception. Interpretation of our research work could vary, depending on the worldview of the audience. This is where communication and building arguments become the key of success. Our research, is never a source of truth. It is a source of subjective truth. It is truth based on the glass we decided to put on ourselves. The impact to your research can be driven forward into directions you initially did not imagine. Maybe your designers recognize some other interesting insights about your customers, so they focus on that path. And it's okay.

It's folly for us, as researchers, to think of research only at the realm of conception, often times forgetting that the magic often happens in the realm of execution and perception. Keeping your eyes open for possibilities is indeed, like artists, one of the most important thing in creating a work of art.

### On mistakes, trial and error
> "Not every stone, wood, are the same. They can react differently even when you use the same tools. Learnings are made, not prepared for, just as those discoveries are found…"

He explained to me on how he created a statue of Wishnu out of a chunk of mahogany, and failed. The failed wood sculpting is left half-sculpted on the god's lower body, and then the wood cracks into two pieces. He made a mistake when trying to carve an opening with a flat-edge chisel. He didn't throw away the broken pieces, instead of pivoting into creating another sculpt, the torso of the god himself, and the lower body transformed into another block of wooden flowers.

Just like research work. We dive into the process, and we found out that some of our tools and frameworks did not generate the kind of data we wanted. The interview guide we executed failed to dig deep into insights we're hoping for. It's normal. The artisan taught me, when failure in research arise, it's not wise to discard the result, or the ongoing approach. 

There are always something we can make out of that. When participants are ready in front of you, talking to you, ready to share their opinions and stories, there are always things that you can explore. There are always new forms of insight that you can gain. It's just a matter of how prepared are you to find another route to discovery and opportunities. The question is, how are you ready for an unplanned exploration, when it suddenly seem like a dead-end?

I remember one time, watching one of episode from "The Joy of Painting", when Bob Ross said: "We don't make mistakes, just happy little accidents. When it's your world, you can decide what to make."

### On achievement
> "My greatest achievement?"
> He looked around his workshop, looking at hundreds of artwork he had created…
> "This…"
> He did not point at any sculpting he made. He raised both his hand, and showed me his palms.

For an artisan, achievement is not really the end product. Or at least it was not always the end product. For this one particular wood sculptor, it is all about the process in the middle the new discoveries and the steps he took to create numerous work of art. The small iteration he added to his experience, the knowledge he gained in order to determine how to navigate an unknown wood block, the intuition he had acquired when every piece of wood reacted to his hammering, his snap judgements. And eventually, his expertise.

As a researcher, I don't think it's the research result that are the main achievement. But rather, the acquired experience of it. Research results are just like an artists' artworks. It's like a piece of music, a paintings, and a sculpting. In the end, it's just objects. It could be timeless, and it could be meaningless. But In the end, it's just a vessel for the artists' self development and journey of discovery. 

The same could be said for a researcher. We're artists of our crafts. The main achievement a researcher can get, is always about the experience, the knowledge we gain in order to navigate an unknown phenomenon, the intuition we had acquired when interviews and observation data is presented to our eyes, the snap judgement we have when we're in the field, and the attention to new details in each every research project. 

I remember once my exchange with one of my first mentors. I asked him _"How do I create great research? Because I wanted to feel the achievement of it."_

And he looked back at me, confused, and then replied _"Of all the research projects that you've done, did they have an impact to you?"_

_"If you do research, and you feel like it doesn't have any impact on you, there is no purpose of you doing it in the first place. In fact, I bet the research itself, is already useless…"_

### On wisdom
> "Hahaha, no, I'm will never say that I'm wise… I'm a sculptor, that's all there is…"

Wisdom, can't be taught. Wisdom can't be said. Wisdom isn't something you can structure into words, and preach to other people. Learning from this wood sculptor, I see it with my own eyes that wisdom lies in actions, in perseverance, continuity, and contribution. 

As researchers, it's important for us to think about our work as a piece of art. The more we perceive it as art, the more attention we put to it, and the more open we are to new learnings and opportunities. The kind of quality we can produce are grounded with genuine, and heartfelt dedication. We started to put our faith into the whole process instead of the end goal. We can learn to constantly check our research vision, not only in conception, but also in its execution, and also perception. We can focus less on tools, jargons, and frameworks, as we understand the limitations of each within our settings. 

And lastly, it was because of this exchange with this Balinese wood sculptor, I realize that it was the contribution that matters. It's more about how the work we create can impact other people (or businesses). We are researchers, that's all there is. And I think, to realize that achievements lie on the continuous process and iteration, it's the best wisdom a researcher can obtain.